Repository astropy/ci-helpers, pull requests merged in 2018-11, with the labels that each got.

#336 Upgrade pip to the latest version
  .travis.yml
  appveyor/install-miniconda.ps1
  travis/setup_dependencies_common.sh
Labels: merge-when-ci-passes

#338 pip fallback install to honour non exact version number
  .travis.yml
  test_env.py
  travis/setup_dependencies_common.sh
Labels: travis

#340 Unpin pytest<3.7 in Travis and Appveyor
  appveyor/pinned
  test_env.py
  travis/setup_dependencies_common.sh
Labels: merge-when-ci-passes

#330 Adding utility function to test importing all submodules from packages
  README.md
  utils/import_submodules.py
Labels: enhancement, merge-when-ci-passes

#341 pip fallback install should really honour non exact version number
  .travis.yml
  travis/setup_dependencies_common.sh
Labels: merge-when-ci-passes

#345 Adding PYTEST_VERSION for appveyor
  appveyor.yml
  appveyor/install-miniconda.ps1
Labels: appveyor

#347 Making sure pytest version is correctly handled by pip
  .travis.yml
  travis/setup_dependencies_common.sh
Labels: bug, travis
